[[redirects]]
  from = "/"
  to = "/index-zh.html"
  status = 301
  force = false
  conditions = {Language = ["zh"]}

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'https://tauhu.tw/' 'https://fonts.googleapis.com/' 'https://use.fontawesome.com/' 'unsafe-inline'"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options = "DENY"
	X-XSS-Protection = "1; mode=block"